import XcodeProj

extension Generator {
    /// Creates an `XCUserData`.
    static func createXCUserData(
        userName: String,
        customSchemes: [XCScheme],
        autogeneratedSchemes: [AutogeneratedScheme]
    ) -> XCUserData {
        let sortedAutogeneratedSchemes = autogeneratedSchemes
            .sorted { lhs, rhs in
                // xor, compare productType then alphabetical if
                // both scheme have the same productType
                guard
                    lhs.productTypeSortOrder == rhs.productTypeSortOrder
                else {
                    return lhs.productTypeSortOrder < rhs.productTypeSortOrder
                }
                
                return lhs.scheme.name < rhs.scheme.name
            }
            .map(\.scheme)

        let schemeUserStates = (customSchemes + sortedAutogeneratedSchemes)
            .enumerated()
            .map { index, scheme in
                let isShown = !(scheme.name.hasSuffix("_objc") || scheme.name.hasSuffix("_swift"))
                return XCSchemeManagement.UserStateScheme(
                    name: "\(scheme.name).xcscheme",
                    shared: true,
                    orderHint: index,
                    isShown: isShown
                )
            }
        
        return XCUserData(
            userName: userName,
            schemes: [],
            schemeManagement: XCSchemeManagement(
                schemeUserState: schemeUserStates
            )
        )
    }
}
